# Generated by Django 2.1.7 on 2019-02-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player1_result',
            new_name='player1_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2_result',
            new_name='player2_score',
        ),
    ]
