# Generated by Django 2.1.7 on 2019-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190222_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(max_length=30, verbose_name='Player 1 name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0, verbose_name='Player 1 score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(max_length=30, verbose_name='Player 2 name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0, verbose_name='Player 2 score'),
        ),
    ]
